### ISSUE TITLE
DHT11 sensor driver needed

### ISSUE THREAD

**Issue by Copypeng** [hybridgroup/cylon-gpio#32]
this DHT11 is a sensor for measuring temperature and humidity.

http://playground.arduino.cc/main/DHT11Lib

I test it with the Analog Sensor driver, it works,but the data looks like the total of the temperature value and the humidity value.

so, can add the driver of DHT11 like sensor ?

**Comment by edgarsilva** [comment]
@Copypeng for some reason this issue went unnoticed, not sure what boards support the communication protocol from this sensor. It seems you would need to import or convert the DHT library to be able to read the sensor data.

Let me know if you had any luck with this, maybe this information would be useful to other people.

I'm closing this issue since it is pretty old, we can reopen and follow up if needed.
